language: go
go_import_path: github.com/33cn/plugin
sudo: false
notifications:
  email: false
jobs:
  include:
    - stage: test
      sudo: require
      install:
        - go get -u gopkg.in/alecthomas/gometalinter.v2
        - go get -u mvdan.cc/sh/cmd/shfmt
        - go get -u mvdan.cc/sh/cmd/gosh
        - sudo apt install clang-format
        - sudo apt install shellcheck
      os: linux
      dist: xenial
      go:
        - "1.9"
        - master
      script:
        #- make test
        - make fmt
        - make checkgofmt
        - make linter
